./advanced_tests -p ../kgovinda/abt -r ./run_experiments
./advanced_tests -p ../kgovinda/gbn -r ./run_experiments
./advanced_tests -p ../kgovinda/sr -r ./run_experiments
./basic_tests -p ../kgovinda/abt -r ./run_experiment
./basic_tests -p ../kgovinda/gbn -r ./run_experiment
./basic_tests -p ../kgovinda/sr -r ./run_experiment
./sanity_tests -p ../kgovinda/abt -r ./run_experiments
./sanity_tests -p ../kgovinda/gbn -r ./run_experiments
./sanity_tests -p ../kgovinda/sr -r ./run_experiments